export const routes = {
  LoginPage: "/login",
  ErrorConnectPage: "/error",
  ResetPasswordPage: "/reset-password",
  ForgotPasswordPage: "/forgot-password",
  EditPage: "/contract-management/detail/edit/:contractCode",
  ProfilePage: "/profile",
  ContractPage: "/contract-management",
  DetailPage: "/contract-management/detail/:contractCode",
  AddPage: "/contract-management/add",
  RecordPage: "/record",
  EditRecordPage: "/record/edit/:recordId",
  PlaylistPage: "/playlist",
  PlaylistDetailPage: "/playlist/detail/:playlistId",
  AddPlaylistPage: "/playlist/add-playlist",
  AddPlaylistRecordPage: "/playlist/add-playlist/add-records",
  PlaylistSchedulePage: "/playlist-schedule",
  PlaylistScheduleDetailPage: "/playlist-schedule/detail/:playlistScheduleCode",
  EditPlaylistSchedulePage: "/playlist-schedule/detail/edit/:playlistScheduleCode",
};
