export const routes = {
  LoginPage: "/",
  ErrorConnectPage: "/error",
  ResetPasswordPage: "/reset-password",
  ForgotPasswordPage: "/forgot-password",
  EditPage: "/contract-management/detail/edit/:contractCode",
  ProfilePage: "/profile",
  ContractPage: "/contract-management",
  DetailPage: "/contract-management/detail/:contractCode",
  AddPage: "/contract-management/add",
  RecordPage: "/record",
  EditRecordPage: "/record/edit/:recordId",
  PlaylistPage: "/playlist",
  PlaylistDetailPage: "/playlist/detail/:playlistId",
  AddPlaylistPage: "/playlist/add-playlist",
  AddPlaylistRecordPage: "/playlist/add-playlist/add-records",
  PlaylistSchedulePage: "/playlist-schedule",
  PlaylistScheduleDetailPage: "/playlist-schedule/detail/:playlistScheduleCode",
  EditPlaylistSchedulePage:
    "/playlist-schedule/detail/edit/:playlistScheduleCode",
  RevenueReportPage: "/revenue/report",
  RevenueDistributionPage: "/revenue/distribution",
  RevenueDistributionDetailPage: "/revenue/distribution/detail/:id",
  RevenueReportDetailPage: "/revenue/report/detail",
  RevenueReportContractDetailPage: "/revenue/report/detail/contract/:id",
  UnitUsedManagementPage: "/unit-used-management",
  UnitUsedManagementDetailPage: "/unit-used-management/detail/:id",
  UserOfUnitUsedManagementDetailPage:
    "/unit-used-management/detail/:contractId/user/:userId",
  AddUserOfUnitUsedManagementPage: "/unit-used-management/detail/:id/user/add",
  ForControlHistoryPage: "/for-control/history",
  ForControlHistoryDetailPage: "/for-control/history/detail/:id",
  AuthorizedUserPage: "/authorization/user",
  AuthorizedEditUserPage: "/authorization/user/:id/edit",
  AuthorizedAddUserPage: "/authorization/user/add",
  AuthorizedEditRolePage: "/authorization/role/edit/:id",
  AuthorizedAddRolePage: "/authorization/role/add",
  SettingForControlPage: "/setting/for-control",
  SupportUserManualPage: "/support/user-manual",
  AuthorizedPartnerPage: "/authorized-partner",
  EditAuthorizedPartnerPage: "/authorized-partner/edit/:id",
  DevicePage: "/device-management",
  DeviceDetailPage: "/device-management/detail/:id",
  SettingPage: "/system-setting",
  CategoryPage: "/category",
  EditCategoryPage: "/category/edit",
  DownloadPage: "/download",
  FeedbackPage: "/feedback",
  EntrustmentContractDetail:
    "/contract-management/entrustment-contract/detail/:id",
  AddEntrustmentContractPage: "/contract-management/entrustment-contract/add",
  ManagementContractTypePage: "/setting/contract-management",
  EditWarningExpirePage: "/setting/contract-management/edit",
  EditContractTypePage: "/setting/contract-management/edit-contract-type",
};
